### ISSUE TITLE
Android app crashes after entering credentials

### ISSUE THREAD

**Issue by 7patricia** [plaid/react-native-plaid-link-sdk#117]
Hi! 

I'm having an issue using your SDK on Android.

I followed the installation instructions and I am using v3.1.2.

The SDK opens and everything works fine until I click "Continue" after logging into a bank with success. When I do that the app crashes and there's the following error on the logcat: 

`2020-05-04 09:33:24.580 14026-14026/com.myapp.sandbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.sandbox, PID: 14026
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=100, data=Intent { (has extras) }} to activity {com.myapp.sandbox/com.myapp.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:25)
        at com.plaid.PlaidModule.onActivityResult(PlaidModule.kt:247)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.jumio.react.JumioActivity.onActivityResult(JumioActivity.java:278)
        at android.app.Activity.dispatchActivityResult(Activity.java:7762)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) ` 

Does anybody know why this happens?

Seems to be related with https://github.com/plaid/react-native-plaid-link-sdk/issues/75, but that should be fixed by now right?

**Comment by JeroenMols** [comment]
Hi @7patricia, thanks for filing an issue!

We are currently able to reproduce a similar error by rapidly clicking the "open link" button in our sample application. In that case our SDK effectively gets opened twice, resulting in a double callback after successfully completing the flow. We are currently working on a fix for that and will ship that (likely) in the next release.

In the mean time, you can avoid duplicate button clicks by using a [DebouncingClickListener](https://github.com/premacck/facilis/blob/ac0e15b7dfee1747dd1932773039fde3c80471eb/facilis/src/main/java/com/prembros/facilis/util/DebouncingClickListener.kt) or temporary disable the button after a click is received.

Please let us know whether that solves your issue.

**Comment by zsweigart** [comment]
Hi @7patricia we have released a new version today 3.3.0. Please let us know if it resolves your issue!

**Comment by JeroenMols** [comment]
Hi @7patricia , We haven't heard back from you in more than 30 days, so we're assuming this is no longer an issue for you. Please don't hesitate to reopen/file a new issue should your problem persist.
