### ISSUE TITLE
onSuccess in iOS is missing mask in object but exists in metadata_json

### ISSUE THREAD

**Issue by bjjeong** [plaid/react-native-plaid-link-sdk#220]
# The problem

On iOS, I am trying to get the account `mask` that is returned in the `onSuccess` callback but it always comes up as blank in the JS object although it exists in `metadata_json`. The `mask` is correctly filled in on Android.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | No                |
| Occurs on iOS     | Yes                |
| iOS Version           | 14.0                |
| iOS Devices/Emulators               |  iPhone 11 Pro                |

# Steps to Reproduce

1. Open Plaid link
2. Enter sandbox credentials for any bank.
3. Select account and confirm.
4. Log contents of `onSuccess` callback.

My `onSuccess` callback result:
```
{
  "public_token": "omitted",
  "metadata": {
    "institution": {
      "name": "Regions Bank",
      "institution_id": "ins_19"
    },
    "accounts": [
      {
        "verification_status": "",
        "mask": "", <----------- The value is empty, even though you can clearly see "0000" in metadata_json
        "name": "Plaid Checking",
        "subtype": "checking",
        "id": "jBgJxR39o4U6mxvRVVQycBkWBZPJvWi1gM9GZ",
        "type": "depository"
      }
    ],
    "metadata_json": "{\"institution\":{\"name\":\"Regions Bank\",\"institution_id\":\"ins_19\"},\"account\":{\"id\":\"jBgJxR39o4U6mxvRVVQycBkWBZPJvWi1gM9GZ\",\"name\":\"Plaid Checking\",\"type\":\"depository\",\"subtype\":\"checking\",\"mask\":\"0000\",\"verification_status\":null},\"account_id\":\"jBgJxR39o4U6mxvRVVQycBkWBZPJvWi1gM9GZ\",\"accounts\":[{\"id\":\"jBgJxR39o4U6mxvRVVQycBkWBZPJvWi1gM9GZ\",\"name\":\"Plaid Checking\",\"mask\":\"0000\",\"type\":\"depository\",\"subtype\":\"checking\",\"verification_status\":null}],\"link_session_id\":\"5a91f0d0-b00b-4fdb-87f6-76f4026f151e\",\"public_token\":\"omitted"}",
    "link_session_id": "5a91f0d0-b00b-4fdb-87f6-76f4026f151e"
  }
}
```

# Expected Result
I expect the `mask` value to match what is returned in `metadata_json`.

**Comment by amytang0** [comment]
Hey, this should be fixed with if you update your LinkKit pod to `2.0.5`. Please re-open if this still reproes!

**Comment by bjjeong** [comment]
@amytang0 Hi, unfortunately I'm still getting the empty mask in LinkKit `2.0.5`. I'm on `react-native-plaid-link-sdk@^6.0.3-rc2` as well.

**Comment by pladaub** [comment]
I've validated that the fix in 2.05 does behave correctly on our end. Have you cleaned your build directory and recompiled?
