### ISSUE TITLE
Plaid fails to launch on Android 7.0.0

### ISSUE THREAD

**Issue by jennifersalas** [plaid/react-native-plaid-link-sdk#440]
# The problem
On android 7.0.0, launching plaid SDK fails to start and crashes the app. Not observable on latest android.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.1.0|
| ReactNative Version     | 0.64.2         |
| Occurs on Android             | Yes |
| Android OS Version                    | 7.0.0 (24) |
| Android Devices/Emulators    | Pixel 4 |
| Occurs on iOS     |  No  |
| iOS Version           | N/A |
| iOS Devices/Emulators               | N/A   |

# Steps to Reproduce
1. Run plaid using `openLink`.
2. Observe the app crashes.

# Expected Result
Plaid SDK launches

# Logs
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/invoke/MethodHandles$Lookup;
        at retrofit2.Platform.<init>(Platform.java:62)
        at retrofit2.Platform$Android.<init>(Platform.java:115)
        at retrofit2.Platform.findPlatform(Platform.java:44)
        at retrofit2.Platform.<clinit>(Platform.java:34)
        at retrofit2.Platform.get(Platform.java:37)
        at retrofit2.Retrofit$Builder.<init>(Retrofit.java:430)
        at com.plaid.internal.m.a(SourceFile:8)
        at com.plaid.internal.m2.get(SourceFile:33)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.plaid.internal.e1.d(SourceFile:1)
        at com.plaid.internal.d1$k0.get(SourceFile:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.plaid.internal.h4.a(SourceFile:50)
        at com.plaid.internal.h4.c(SourceFile:243)
        at com.plaid.internal.d4.a(SourceFile:13)
        at com.plaid.internal.d4$d.invokeSuspend(SourceFile:-1)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.invoke.MethodHandles$Lookup" on path: DexPathList[[zip file "/data/app/{REDACTED}/base.apk"],nativeLibraryDirectories=[/data/app/{REDACTED}/lib/x86, /data/app/{REDACTED}/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at retrofit2.Platform.<init>(Platform.java:62)
        at retrofit2.Platform$Android.<init>(Platform.java:115)
        at retrofit2.Platform.findPlatform(Platform.java:44)
        at retrofit2.Platform.<clinit>(Platform.java:34)
        at retrofit2.Platform.get(Platform.java:37)
        at retrofit2.Retrofit$Builder.<init>(Retrofit.java:430)
        at com.plaid.internal.m.a(SourceFile:8)
        at com.plaid.internal.m2.get(SourceFile:33)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.plaid.internal.e1.d(SourceFile:1)
        at com.plaid.internal.d1$k0.get(SourceFile:1)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.plaid.internal.h4.a(SourceFile:50)
        at com.plaid.internal.h4.c(SourceFile:243)
        at com.plaid.internal.d4.a(SourceFile:13)
        at com.plaid.internal.d4$d.invokeSuspend(SourceFile:-1)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by jennifersalas** [comment]
It appears another library had a similar issue w/ the Lookup method on android api 24/25: https://github.com/square/retrofit/pull/3344

**Comment by amytang0** [comment]
Hi, what version of Retrofit are you using? You are correct that Retrofit does have this issue, and we recommend using at least `com.squareup.retrofit2:retrofit:2.8.2` to circumvent this

**Comment by jennifersalas** [comment]
Hi Amy, we don't use retrofit, that was just an example where they had a similar issue due to `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/invoke/MethodHandles$Lookup`

**Comment by jennifersalas** [comment]
Hi @amytang0, we don't directly use retrofit, I believe this is a dependency of the plaid android sdk.

**Comment by jennifersalas** [comment]
Following up here, after adding `implementation "com.squareup.retrofit2:retrofit:2.9.0"` to the build.gradle file and upgrading react-native-plaid-sdk to 7.2.0, plaid launches, but it is stuck on the loader indefinitely. Again, this is on android api 24/25. Later versions of android do not have this issue.

**Comment by viktorkurochka** [comment]
I have the same issue

**Comment by stingrigs** [comment]
Still reproduced on Android 7.0.0

**Comment by victorious85** [comment]
I have the same problem

**Comment by LovedJohni** [comment]
same problem (
does anyone have a solution?

**Comment by Lapaenergy** [comment]
The same issue =/

**Comment by Bohda-P** [comment]
I have the same problem(

**Comment by NataliiaYakorieva** [comment]
I also have the same issue(

**Comment by amytang0** [comment]
@jennifersalas I can't seem to repro this issue of an infinite spinner with 7.2.0 and `implementation "com.squareup.retrofit2:retrofit:2.9.0"`; would it be possible to share the configuration you are opening Plaid Link with e.g. 
```
const linkTokenProps: PlaidLinkProps = {
    tokenConfig: {
        token: "link-sandbox-3fd3cb51-6c21-4c19-8ec4-e9bc9eeac6e4",
        logLevel: LinkLogLevel.ERROR,
    },
    onSuccess: (success: LinkSuccess) => {
        console.log('Success: ', success);
    }
}
``` 
?

Fyi, loading times can sometimes be slow depending on connection speeds, so if possible, please wait up to 5 minutes to verify that the spinner is indeed indefinite

**Comment by jennifersalas** [comment]
This is just a console log of the params we pass to openLink
```
{
  "tokenConfig": {
    "token": "link-sandbox-ad445fe8-63f0-4bc2-be6d-a6c841289b10",
    "onSuccess":  [onSuccess function]
  }
}
```

**Comment by amytang0** [comment]
Hmm I am indeed not seeing traffic for that link-token; any errors showing in `adb logcat`?

**Comment by jennifersalas** [comment]
Looks like it gets stuck in an infinite loop (it goes on like this forever)
```
2022-01-18 15:05:07.237 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.261 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.297 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.321 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.352 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.369 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.383 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.401 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.413 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.432 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.449 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.475 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.497 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.532 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.555 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.581 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.598 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.613 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.630 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.647 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.664 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.697 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.751 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.777 25212-25223/com.{REDACTED}.{REDACTED}.develop I/art: Background partial concurrent mark sweep GC freed 325(28KB) AllocSpace objects, 5(34MB) LOS objects, 3% free, 97MB/101MB, paused 6.022ms total 102.733ms
2022-01-18 15:05:07.786 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.802 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.821 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.837 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.855 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.871 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.892 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.916 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.949 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:07.981 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.010 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.024 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.040 1720-1928/? D/EGL_emulation: eglMakeCurrent: 0xa9085900: ver 2 0 (tinfo 0xa9083750)
2022-01-18 15:05:08.048 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.066 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.080 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.098 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.113 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.145 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.183 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.208 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.240 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.256 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.272 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.290 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.305 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.320 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.351 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.373 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.407 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.432 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.449 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.465 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.479 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.494 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.517 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.538 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.576 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.610 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
2022-01-18 15:05:08.639 25212-25212/com.{REDACTED}.{REDACTED}.develop W/art: Attempt to remove non-JNI local reference, dumping thread
```

**Comment by amytang0** [comment]
The original Retrofit issue is resolved in `7.2.0`; I'm closing this issue but @jennifersalas, if you still see the infinite spinner, please open a new issue so we can address that.

Thanks yall

**Comment by jarredt** [comment]
@amytang0 to confirm, do you mean it's fixed in `7.2.1` (released today)? We experienced this issue in `7.2.0` (released in November).

**Comment by jennifersalas** [comment]
@amytang0 Still seeing this issue after testing on Samsung Galaxy S8 android v7.0 on browser stack
